scrape_configs:
  - job_name: 'otl-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otl-collector:8889']
      - targets: ['input-service:8080']
      - targets: ['weather-service:8081']